//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISA.Dblib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalogue()
        {
            this.MagasinCatalogues = new HashSet<MagasinCatalogue>();
            this.Pages = new HashSet<Page>();
            this.PrixCatalogueArticles = new HashSet<PrixCatalogueArticle>();
        }
    
        public long Id { get; set; }
        public long IdOperation { get; set; }
        public string Type { get; set; }
        public string Libelle { get; set; }
        public string Vitesse { get; set; }
        public int Largeur { get; set; }
        public int Hauteur { get; set; }
        public Nullable<long> ImportId { get; set; }
    
        public virtual Operation Operation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MagasinCatalogue> MagasinCatalogues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Pages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrixCatalogueArticle> PrixCatalogueArticles { get; set; }
    }
}
