//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISA.Dblib
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagasinCatalogue
    {
        public long Id { get; set; }
        public long IdMagasin { get; set; }
        public long IdCatalogue { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Magasin Magasin { get; set; }
    }
}
