//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISA.Dblib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magasin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magasin()
        {
            this.MagasinCatalogues = new HashSet<MagasinCatalogue>();
        }
    
        public long Id { get; set; }
        public string Libelle { get; set; }
        public Nullable<long> ImportId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MagasinCatalogue> MagasinCatalogues { get; set; }
    }
}
