//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISA.Dblib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Média
    {
        public long Id { get; set; }
        public long IdTypeMedia { get; set; }
        public long IdArticle { get; set; }
        public string Chemin { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual TypeMedia TypeMedia { get; set; }
    }
}
