//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISA.Dblib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrixCatalogueArticle
    {
        public long Id { get; set; }
        public long IdCatalogue { get; set; }
        public long IdArticle { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<decimal> PrixAvantCoupon { get; set; }
        public Nullable<decimal> PrixAvantCroise { get; set; }
        public Nullable<decimal> ReductionEuro { get; set; }
        public Nullable<decimal> ReductionPourcent { get; set; }
        public Nullable<decimal> AvantageEuro { get; set; }
        public Nullable<decimal> AvantagePourcent { get; set; }
        public Nullable<decimal> Ecotaxe { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Catalogue Catalogue { get; set; }
    }
}
